using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class da√±o : MonoBehaviour
{

    private Rigidbody2D Rigidbody2D;
    // Start is called before the first frame update
    void Start()
    {
        Rigidbody2D = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame

    public void DestroyBullet()
    {
        Destroy(gameObject);
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        JohnMovement john = collision.GetComponent<JohnMovement>();
        Grunt grunt = collision.GetComponent<Grunt>();
        if (john != null)
        {
            john.Hit();
        }
    }
}
